import { LengthMetrics } from "@kit.ArkUI"

export const fullSize: string = '100%'

export const halfSize: string = '50%'

export const corner:number=16

export const uniformPadding: number = 16

export const padding1: number = 1
export const padding2: number = 2
export const padding3: number = 3
export const padding4: number = 4
export const padding5: number = 5
export const padding6: number = 6
export const padding8: number = 8

export const padding10: number = 10
export const padding20: number = 20
export const padding30: number = 30
export const padding40: number = 40
export const padding50: number = 50
